service: wso2-release-analyse

provider:
  name: aws
  runtime: nodejs12.x
functions:
  analyse:
    handler: handler.analyse
    events:
      - schedule: rate(1 minute)
    environment:
      SPREADSHEET_ID: 1tYwsLlG8A5-Y8nJI8FXM7E9szkahdQ4cEdqdVDmS43c
      SHEET_NAME: Sheet1
      GITHUB_REPO_OWNER: wso2
      GITHUB_REPO: product-is
