service: wso2-release-analyse

provider:
  name: aws
  runtime: nodejs12.x
functions:
  analyse:
    handler: handler.analyse
    events:
      - schedule: rate(1 minute)
    environment:
      SPREADSHEET_ID: <SPREADSHEET_ID>
      SHEET_NAME: <SHEET_NAME>
      GITHUB_REPO_OWNER: <GITHUB_REPO_OWNER>
      GITHUB_REPO: <GITHUB_REPO>
